name: Test publish

on:
  push:
    branches:
    - master
  repository_dispatch:
    types:
    - publish_latest_tag
    - publish_master

jobs:
  publish_image:
    name: Publish image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - if: github.event_name == 'repository_dispatch'
      name: Repository dispatch
      uses: truebrain/openttd-actions/checkout-dispatch@master

    - name: Checkout tags and submodules
      uses: truebrain/openttd-actions/checkout@master
      with:
        with-tags: true
        with-submodules: true

    - name: Set variables
      id: vars
      uses: truebrain/openttd-actions/docker-vars@master
      with:
        registry-username: ${{ secrets.GHCR_USERNAME }}

    - name: Build
      uses: truebrain/openttd-actions/docker-build@master
      with:
        name: ${{ steps.vars.outputs.name }}
        tag: ${{ steps.vars.outputs.tag }}
        tags: ${{ steps.vars.outputs.tags }}
        version: ${{ steps.vars.outputs.version }}
        date: ${{ steps.vars.outputs.date }}
        registry: ghcr.io

    - if: steps.vars.outputs.dry-run == 'false'
      name: Publish
      id: publish
      uses: truebrain/openttd-actions/docker-publish@master
      with:
        registry-username: ${{ secrets.GHCR_USERNAME }}
        registry-password: ${{ secrets.GHCR_PASSWORD }}
        name: ${{ steps.vars.outputs.name }}
        tag: ${{ steps.vars.outputs.tag }}
        registry: ghcr.io

    - if: steps.vars.outputs.dry-run == 'false'
      name: Trigger deployment
      uses: truebrain/openttd-actions/deployments-create@master
      with:
        ref: ${{ steps.vars.outputs.sha }}
        environment: ${{ steps.vars.outputs.environment }}
        version: ${{ steps.vars.outputs.version }}
        date: ${{ steps.vars.outputs.date }}
        docker-tag: ${{ steps.publish.outputs.remote-tag }}
        github-token: ${{ secrets.DEPLOYMENT_TOKEN }}
